#!/usr/bin/env python
import logging
from Repl import Repl

if __name__ == '__main__':
	import sys
	if '-v' in sys.argv[1:]:
		log_level = logging.DEBUG
	else:
		log_level = logging.WARN
	logging.basicConfig(level=log_level)
	sys.exit(Repl().run())
